// export
var name_to_virtualkey = {
    "ONE": "1",
    "TWO": "2",
    "THREE": "3",
    "FOUR": "4",
    "FIVE": "5",
    "SIX": "6",
    "SEVEN": "7",
    "EIGHT": "8",
    "NINE": "9",
    "ZERO": "0",
    // modifiers
    "RIGHT_SHIFT": "RSHIFT",
    "LEFT_SHIFT": "LSHIFT",
    "SHIFT": "LSHIFT",
    "RIGHT_ALT": "RMENU",
    "LEFT_ALT": "LMENU",
    "ALT": "LMENU",
    "OPTION": "LMENU",
    "RIGHT_CONTROL": "RCONTROL",
    "LEFT_CONTROL": "LCONTROL",
    "CONTROL": "LCONTROL",
    // windows key
    "LEFT_GUI": "LWIN",
    "GUI": "LWIN",
    "WINDOWS": "LWIN",
    "COMMAND": "LWIN",
    "RIGHT_GUI": "RWIN",
    // apps ?
    "APPLICATION": "APPS",
    // other
    "BACKSPACE": "BACK",
    "ENTER": "RETURN",
    "RETURN": "RETURN",
    "CAPS_LOCK": "CAPITAL",
    "SPACEBAR": "SPACE",
    "SPACE": "SPACE",  // use both
    // punctuation or stuff
    "COMMA": "OEM_COMMA",
    "PERIOD": "OEM_PERIOD",
    "EQUALS": "OEM_PLUS",
    "SEMICOLON": "OEM_1",
    "FORWARD_SLASH": "OEM_2",
    "GRAVE_ACCENT": "OEM_3",
    "LEFT_BRACKET": "OEM_4",
    "BACKSLASH": "OEM_5",
    "RIGHT_BRACKET": "OEM_6",
    "QUOTE": "OEM_7",
    "MINUS": "OEM_MINUS",
    "PAGE_DOWN": "NEXT",
    "PAGE_UP": "PRIOR",
    "PRINT_SCREEN": "SNAPSHOT",
    "SCROLL_LOCK": "SCROLL",
    // numpad
    "KEYPAD_NUMLOCK": "NUMLOCK",
    "KEYPAD_FORWARD_SLASH": "DIVIDE",
    "KEYPAD_ASTERISK": "MULTIPLY",
    "KEYPAD_MINUS": "SUBTRACT",
    "KEYPAD_PLUS": "ADD",
    // arrows
    "LEFT_ARROW": "LEFT",
    "RIGHT_ARROW": "RIGHT",
    "UP_ARROW": "UP",
    "DOWN_ARROW": "DOWN",
    // other numpad
    "KEYPAD_ONE": "NUMPAD1",
    "KEYPAD_TWO": "NUMPAD2",
    "KEYPAD_THREE": "NUMPAD3",
    "KEYPAD_FOUR": "NUMPAD4",
    "KEYPAD_FIVE": "NUMPAD5",
    "KEYPAD_SIX": "NUMPAD6",
    "KEYPAD_SEVEN": "NUMPAD7",
    "KEYPAD_EIGHT": "NUMPAD8",
    "KEYPAD_NINE": "NUMPAD9",
    "KEYPAD_ZERO": "NUMPAD0",
    "KEYPAD_PERIOD": "DECIMAL",
    // 'POUND': no US
    // 'POWER': mac ?
};
